# Assignment 8
Using any dataset that has a categorical feature that needs to be predicted, use several algorithms, preprocessing techniques, feature extraction techniques to fit the data to the model and show the accuracy, confusion matrix, and the classification report. G
https://www.kaggle.com/ntnu-testimon/paysim1
https://www.kaggle.com/joniarroba/noshowappointments
https://archive.ics.uci.edu/ml/datasets.html?format=&task=cla&att=&area=&numAtt=&numIns=&type=&sort=nameUp&view=table
https://archive.ics.uci.edu/ml/datasets/default+of+credit+card+clients
https://archive.ics.uci.edu/ml/datasets/Adult

In [16]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn import preprocessing
#import sklearn.preprocessing

from sklearn import linear_model, datasets, svm, neighbors
from sklearn.linear_model import LogisticRegression as LogReg
from sklearn.neighbors import KNeighborsClassifier as KNN

In [17]:
import pandas as pd
adult = pd.read_csv('../data/adult.data.txt', header=None, names = ['age', 'workclass', 
                'fnlwgt','education','education-num','marital-status'
              ,'occupation','relationship','race','sex','capital-gain','capital-loss'
             , 'hours-per-week','native-country','50k'] )

In [18]:
LE = preprocessing.LabelEncoder()
adult['50k'] = LE.fit_transform(adult['50k'])

| <=50k| >50k|
|------|------|
|   0  | 1|

In [19]:
adult['relationship'].value_counts()

 Husband           13193
 Not-in-family      8305
 Own-child          5068
 Unmarried          3446
 Wife               1568
 Other-relative      981
Name: relationship, dtype: int64

In [20]:
relation = LE.fit_transform(adult['relationship'])
adult['relation'] = relation

| Married-civ-spouse| Never-married| Divorced | Separated | Widowed | Married-spouse-absent | Married-AF-spouse|
|------|------|------|------|------|------|------|
|   2  | 4    |0     |5     |6     |3     |1     |

In [21]:
feature_cols = ['age','relation']

X = adult[feature_cols]
X = preprocessing.MinMaxScaler().fit_transform(X)
y = adult['50k']

model = svm.SVC(kernel='linear').fit(X, y)

print(model.intercept_, model.coef_)
print (accuracy_score(y, model.predict(X)))
print(classification_report(y, model.predict(X)))
print(confusion_matrix(y, model.predict(X)))

[-0.99998205] [[  6.70814156e-05  -9.35471096e-05]]
0.759190442554


/Users/JiSunPark/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


             precision    recall  f1-score   support

          0       0.76      1.00      0.86     24720
          1       0.00      0.00      0.00      7841

avg / total       0.58      0.76      0.66     32561

[[24720     0]
 [ 7841     0]]


In [22]:
feature_cols = ['age','relation']

X = adult[feature_cols]
X = preprocessing.MinMaxScaler().fit_transform(X)
y = adult['50k']

model = svm.SVC(kernel='rbf').fit(X, y)

print(accuracy_score(y, model.predict(X)))
print(classification_report(y, model.predict(X)))
print(confusion_matrix(y, model.predict(X)))

0.759190442554


/Users/JiSunPark/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


             precision    recall  f1-score   support

          0       0.76      1.00      0.86     24720
          1       0.00      0.00      0.00      7841

avg / total       0.58      0.76      0.66     32561

[[24720     0]
 [ 7841     0]]


In [23]:
feature_cols = ['age','relation']

X = adult[feature_cols]
X = preprocessing.MinMaxScaler().fit_transform(X)
y = adult['50k']

model = LogReg(C=5).fit(X, y)

print(accuracy_score(y, model.predict(X)))
print(classification_report(y, model.predict(X)))
print(confusion_matrix(y, model.predict(X)))

0.747458616136
             precision    recall  f1-score   support

          0       0.76      0.97      0.85     24720
          1       0.29      0.03      0.06      7841

avg / total       0.65      0.75      0.66     32561

[[24066   654]
 [ 7569   272]]


In [24]:
feature_cols = ['age','relation']

X = adult[feature_cols]
X = preprocessing.MinMaxScaler().fit_transform(X)
y = adult['50k']

model = LogReg(C=10).fit(X, y)

print(accuracy_score(y, model.predict(X)))
print(classification_report(y, model.predict(X)))
print(confusion_matrix(y, model.predict(X)))

0.747458616136
             precision    recall  f1-score   support

          0       0.76      0.97      0.85     24720
          1       0.29      0.03      0.06      7841

avg / total       0.65      0.75      0.66     32561

[[24066   654]
 [ 7569   272]]


In [25]:
feature_cols = ['age','relation']

X = adult[feature_cols]
X = preprocessing.MinMaxScaler().fit_transform(X)
y = adult['50k']

model = KNN(n_neighbors=5).fit(X, y)

print(accuracy_score(y, model.predict(X)))
print(classification_report(y, model.predict(X)))
print(confusion_matrix(y, model.predict(X)))

0.750314793772
             precision    recall  f1-score   support

          0       0.82      0.85      0.84     24720
          1       0.48      0.42      0.45      7841

avg / total       0.74      0.75      0.74     32561

[[21127  3593]
 [ 4537  3304]]


In [26]:
feature_cols = ['age','relation']

X = adult[feature_cols]
X = preprocessing.MinMaxScaler().fit_transform(X)
y = adult['50k']

model = KNN(n_neighbors=7).fit(X, y)

print(accuracy_score(y, model.predict(X)))
print(classification_report(y, model.predict(X)))
print(confusion_matrix(y, model.predict(X)))

0.759835385891
             precision    recall  f1-score   support

          0       0.83      0.85      0.84     24720
          1       0.50      0.46      0.48      7841

avg / total       0.75      0.76      0.76     32561

[[21115  3605]
 [ 4215  3626]]


After comparing the confusion matrix and accuracy scores, it looks like that the best model for these features were KNN (n_neighbors=7)

In [27]:
# test to see if NOT transforming X will make a difference
feature_cols = ['age','relation']

X = adult[feature_cols]
y = adult['50k']

model = KNN(n_neighbors=7).fit(X, y)

print(accuracy_score(y, model.predict(X)))
print(classification_report(y, model.predict(X)))
print(confusion_matrix(y, model.predict(X)))

0.76656122355
             precision    recall  f1-score   support

          0       0.82      0.89      0.85     24720
          1       0.52      0.37      0.43      7841

avg / total       0.75      0.77      0.75     32561

[[22095  2625]
 [ 4976  2865]]


Not transforming X decreased the accuracy score and most of the values in the confusion matrix. Therefore, it is beneficial to transform X.

In [28]:
onehot = preprocessing.OneHotEncoder(sparse=False)
relation_columns = onehot.fit_transform(adult[['relation']])
re_df = pd.DataFrame(relation_columns)
re_df.columns = ["re" + str(i) for i in range(0, 6)]
adult2 = pd.concat([adult, re_df], axis=1)

In [29]:
feature_cols = ['age','re0', 're1', 're2','re3', 're4', 're5']

X = adult2[feature_cols]
X = preprocessing.MinMaxScaler().fit_transform(X)
y = adult2['50k']

model = KNN(n_neighbors=7).fit(X, y)

print(accuracy_score(y, model.predict(X)))
print(classification_report(y, model.predict(X)))
print(confusion_matrix(y, model.predict(X)))

0.762630140352
             precision    recall  f1-score   support

          0       0.81      0.89      0.85     24720
          1       0.51      0.36      0.42      7841

avg / total       0.74      0.76      0.75     32561

[[22032  2688]
 [ 5041  2800]]


One hot encoding did not make a significant change to the accuracy score and the confusion matrix values.